FROM alpine/git as gitclone
WORKDIR /app
RUN git clone https://github.com/kunchalavikram1427/maven-employee-web-application.git

FROM maven:3.8.2-openjdk-11 as build
WORKDIR /app
COPY --from=gitclone /app/maven-employee-web-application/ ./
RUN mvn package

FROM tomcat:9.0
COPY --from=build /app/target/employee-application.war /usr/local/tomcat/webapps
EXPOSE 8080
